name: Anti-Exfil Review

on:
  push:
    branches:
      - anti-exfil-review-v1-ci
  workflow_dispatch:

permissions:
  contents: read

env:
  JDK_JAVAC_OPTIONS: '-Xlint:-module'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: recursive
      - uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # v5.5.0
        with:
          distribution: temurin
          java-version: '25.0.2'
      - name: Run tests
        run: ./gradlew test
